// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	plugin.proto

It has these top-level messages:
	Empty
	InstanceInfo
	InstanceState
	EphemeralState
	ResourceAttrDiff
	InstanceDiff
	ApplyRequest
	ApplyResponse
	ResourceConfig
	ConfigureRequest
	DataSourcesResponse
	DiffRequest
	DiffResponse
	GetSchemaRequest
	GetSchemaResponse
	ImportStateRequest
	ImportStateResponse
	InputRequest
	InputResponse
	ReadDataApplyRequest
	ReadDataApplyResponse
	ReadDataDiffRequest
	ReadDataDiffResponse
	RefreshRequest
	RefreshResponse
	ResourceType
	ResourcesResponse
	ValidateRequest
	ValidateResponse
	ValidateDataSourceRequest
	ValidateResourceRequest
	ProvisionerApplyRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DiffAttrType int32

const (
	DiffAttrType_UNKNOWN DiffAttrType = 0
	DiffAttrType_INPUT   DiffAttrType = 1
	DiffAttrType_OUTPUT  DiffAttrType = 2
)

var DiffAttrType_name = map[int32]string{
	0: "UNKNOWN",
	1: "INPUT",
	2: "OUTPUT",
}
var DiffAttrType_value = map[string]int32{
	"UNKNOWN": 0,
	"INPUT":   1,
	"OUTPUT":  2,
}

func (x DiffAttrType) String() string {
	return proto1.EnumName(DiffAttrType_name, int32(x))
}
func (DiffAttrType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InstanceInfo struct {
	Id         string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type       string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	ModulePath []string `protobuf:"bytes,3,rep,name=module_path,json=modulePath" json:"module_path,omitempty"`
}

func (m *InstanceInfo) Reset()                    { *m = InstanceInfo{} }
func (m *InstanceInfo) String() string            { return proto1.CompactTextString(m) }
func (*InstanceInfo) ProtoMessage()               {}
func (*InstanceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InstanceInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InstanceInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *InstanceInfo) GetModulePath() []string {
	if m != nil {
		return m.ModulePath
	}
	return nil
}

type InstanceState struct {
	Id         string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Attributes map[string][]byte `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ephemeral  *EphemeralState   `protobuf:"bytes,3,opt,name=ephemeral" json:"ephemeral,omitempty"`
	// using json for now
	Meta    []byte `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Tainted bool   `protobuf:"varint,5,opt,name=tainted" json:"tainted,omitempty"`
}

func (m *InstanceState) Reset()                    { *m = InstanceState{} }
func (m *InstanceState) String() string            { return proto1.CompactTextString(m) }
func (*InstanceState) ProtoMessage()               {}
func (*InstanceState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InstanceState) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InstanceState) GetAttributes() map[string][]byte {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *InstanceState) GetEphemeral() *EphemeralState {
	if m != nil {
		return m.Ephemeral
	}
	return nil
}

func (m *InstanceState) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *InstanceState) GetTainted() bool {
	if m != nil {
		return m.Tainted
	}
	return false
}

type EphemeralState struct {
	Type     string            `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ConnInfo map[string]string `protobuf:"bytes,2,rep,name=conn_info,json=connInfo" json:"conn_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *EphemeralState) Reset()                    { *m = EphemeralState{} }
func (m *EphemeralState) String() string            { return proto1.CompactTextString(m) }
func (*EphemeralState) ProtoMessage()               {}
func (*EphemeralState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EphemeralState) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EphemeralState) GetConnInfo() map[string]string {
	if m != nil {
		return m.ConnInfo
	}
	return nil
}

type ResourceAttrDiff struct {
	Old         string       `protobuf:"bytes,1,opt,name=old" json:"old,omitempty"`
	New         string       `protobuf:"bytes,2,opt,name=new" json:"new,omitempty"`
	NewComputed bool         `protobuf:"varint,3,opt,name=new_computed,json=newComputed" json:"new_computed,omitempty"`
	NewRemoved  bool         `protobuf:"varint,4,opt,name=new_removed,json=newRemoved" json:"new_removed,omitempty"`
	NewExtra    []byte       `protobuf:"bytes,5,opt,name=new_extra,json=newExtra,proto3" json:"new_extra,omitempty"`
	RequiresNew bool         `protobuf:"varint,6,opt,name=requires_new,json=requiresNew" json:"requires_new,omitempty"`
	Sensitive   bool         `protobuf:"varint,7,opt,name=sensitive" json:"sensitive,omitempty"`
	Type        DiffAttrType `protobuf:"varint,8,opt,name=type,enum=proto.DiffAttrType" json:"type,omitempty"`
}

func (m *ResourceAttrDiff) Reset()                    { *m = ResourceAttrDiff{} }
func (m *ResourceAttrDiff) String() string            { return proto1.CompactTextString(m) }
func (*ResourceAttrDiff) ProtoMessage()               {}
func (*ResourceAttrDiff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResourceAttrDiff) GetOld() string {
	if m != nil {
		return m.Old
	}
	return ""
}

func (m *ResourceAttrDiff) GetNew() string {
	if m != nil {
		return m.New
	}
	return ""
}

func (m *ResourceAttrDiff) GetNewComputed() bool {
	if m != nil {
		return m.NewComputed
	}
	return false
}

func (m *ResourceAttrDiff) GetNewRemoved() bool {
	if m != nil {
		return m.NewRemoved
	}
	return false
}

func (m *ResourceAttrDiff) GetNewExtra() []byte {
	if m != nil {
		return m.NewExtra
	}
	return nil
}

func (m *ResourceAttrDiff) GetRequiresNew() bool {
	if m != nil {
		return m.RequiresNew
	}
	return false
}

func (m *ResourceAttrDiff) GetSensitive() bool {
	if m != nil {
		return m.Sensitive
	}
	return false
}

func (m *ResourceAttrDiff) GetType() DiffAttrType {
	if m != nil {
		return m.Type
	}
	return DiffAttrType_UNKNOWN
}

type InstanceDiff struct {
	Attributes     map[string]*ResourceAttrDiff `protobuf:"bytes,1,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Destroy        bool                         `protobuf:"varint,2,opt,name=destroy" json:"destroy,omitempty"`
	DestroyDeposed bool                         `protobuf:"varint,3,opt,name=destroy_deposed,json=destroyDeposed" json:"destroy_deposed,omitempty"`
	DestroyTainted bool                         `protobuf:"varint,4,opt,name=destroy_tainted,json=destroyTainted" json:"destroy_tainted,omitempty"`
	// all meta is json for now
	Meta []byte `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (m *InstanceDiff) Reset()                    { *m = InstanceDiff{} }
func (m *InstanceDiff) String() string            { return proto1.CompactTextString(m) }
func (*InstanceDiff) ProtoMessage()               {}
func (*InstanceDiff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InstanceDiff) GetAttributes() map[string]*ResourceAttrDiff {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *InstanceDiff) GetDestroy() bool {
	if m != nil {
		return m.Destroy
	}
	return false
}

func (m *InstanceDiff) GetDestroyDeposed() bool {
	if m != nil {
		return m.DestroyDeposed
	}
	return false
}

func (m *InstanceDiff) GetDestroyTainted() bool {
	if m != nil {
		return m.DestroyTainted
	}
	return false
}

func (m *InstanceDiff) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ApplyRequest struct {
	Info  *InstanceInfo  `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	State *InstanceState `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Diff  *InstanceDiff  `protobuf:"bytes,3,opt,name=diff" json:"diff,omitempty"`
}

func (m *ApplyRequest) Reset()                    { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string            { return proto1.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()               {}
func (*ApplyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ApplyRequest) GetInfo() *InstanceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ApplyRequest) GetState() *InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ApplyRequest) GetDiff() *InstanceDiff {
	if m != nil {
		return m.Diff
	}
	return nil
}

type ApplyResponse struct {
	State *InstanceState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (m *ApplyResponse) Reset()                    { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string            { return proto1.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()               {}
func (*ApplyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ApplyResponse) GetState() *InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

type ResourceConfig struct {
	ComputedKeys []string          `protobuf:"bytes,1,rep,name=computed_keys,json=computedKeys" json:"computed_keys,omitempty"`
	Raw          map[string][]byte `protobuf:"bytes,2,rep,name=raw" json:"raw,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Config       map[string][]byte `protobuf:"bytes,3,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ResourceConfig) Reset()                    { *m = ResourceConfig{} }
func (m *ResourceConfig) String() string            { return proto1.CompactTextString(m) }
func (*ResourceConfig) ProtoMessage()               {}
func (*ResourceConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ResourceConfig) GetComputedKeys() []string {
	if m != nil {
		return m.ComputedKeys
	}
	return nil
}

func (m *ResourceConfig) GetRaw() map[string][]byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *ResourceConfig) GetConfig() map[string][]byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type ConfigureRequest struct {
	ResourceConfig *ResourceConfig `protobuf:"bytes,1,opt,name=resource_config,json=resourceConfig" json:"resource_config,omitempty"`
}

func (m *ConfigureRequest) Reset()                    { *m = ConfigureRequest{} }
func (m *ConfigureRequest) String() string            { return proto1.CompactTextString(m) }
func (*ConfigureRequest) ProtoMessage()               {}
func (*ConfigureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ConfigureRequest) GetResourceConfig() *ResourceConfig {
	if m != nil {
		return m.ResourceConfig
	}
	return nil
}

type DataSourcesResponse struct {
	DataSources []string `protobuf:"bytes,1,rep,name=data_sources,json=dataSources" json:"data_sources,omitempty"`
}

func (m *DataSourcesResponse) Reset()                    { *m = DataSourcesResponse{} }
func (m *DataSourcesResponse) String() string            { return proto1.CompactTextString(m) }
func (*DataSourcesResponse) ProtoMessage()               {}
func (*DataSourcesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DataSourcesResponse) GetDataSources() []string {
	if m != nil {
		return m.DataSources
	}
	return nil
}

type DiffRequest struct {
	Info   *InstanceInfo   `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	State  *InstanceState  `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Config *ResourceConfig `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *DiffRequest) Reset()                    { *m = DiffRequest{} }
func (m *DiffRequest) String() string            { return proto1.CompactTextString(m) }
func (*DiffRequest) ProtoMessage()               {}
func (*DiffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DiffRequest) GetInfo() *InstanceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DiffRequest) GetState() *InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *DiffRequest) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type DiffResponse struct {
	Diff *InstanceDiff `protobuf:"bytes,1,opt,name=diff" json:"diff,omitempty"`
}

func (m *DiffResponse) Reset()                    { *m = DiffResponse{} }
func (m *DiffResponse) String() string            { return proto1.CompactTextString(m) }
func (*DiffResponse) ProtoMessage()               {}
func (*DiffResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DiffResponse) GetDiff() *InstanceDiff {
	if m != nil {
		return m.Diff
	}
	return nil
}

type GetSchemaRequest struct {
	ResourceTypes []string `protobuf:"bytes,1,rep,name=resource_types,json=resourceTypes" json:"resource_types,omitempty"`
	DataSources   []string `protobuf:"bytes,2,rep,name=data_sources,json=dataSources" json:"data_sources,omitempty"`
}

func (m *GetSchemaRequest) Reset()                    { *m = GetSchemaRequest{} }
func (m *GetSchemaRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetSchemaRequest) ProtoMessage()               {}
func (*GetSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetSchemaRequest) GetResourceTypes() []string {
	if m != nil {
		return m.ResourceTypes
	}
	return nil
}

func (m *GetSchemaRequest) GetDataSources() []string {
	if m != nil {
		return m.DataSources
	}
	return nil
}

type GetSchemaResponse struct {
	Schema []byte `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (m *GetSchemaResponse) Reset()                    { *m = GetSchemaResponse{} }
func (m *GetSchemaResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetSchemaResponse) ProtoMessage()               {}
func (*GetSchemaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetSchemaResponse) GetSchema() []byte {
	if m != nil {
		return m.Schema
	}
	return nil
}

type ImportStateRequest struct {
	Id   string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Info *InstanceInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *ImportStateRequest) Reset()                    { *m = ImportStateRequest{} }
func (m *ImportStateRequest) String() string            { return proto1.CompactTextString(m) }
func (*ImportStateRequest) ProtoMessage()               {}
func (*ImportStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ImportStateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ImportStateRequest) GetInfo() *InstanceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ImportStateResponse struct {
	State []*InstanceState `protobuf:"bytes,1,rep,name=state" json:"state,omitempty"`
}

func (m *ImportStateResponse) Reset()                    { *m = ImportStateResponse{} }
func (m *ImportStateResponse) String() string            { return proto1.CompactTextString(m) }
func (*ImportStateResponse) ProtoMessage()               {}
func (*ImportStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ImportStateResponse) GetState() []*InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

type InputRequest struct {
	Id     int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Config *ResourceConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *InputRequest) Reset()                    { *m = InputRequest{} }
func (m *InputRequest) String() string            { return proto1.CompactTextString(m) }
func (*InputRequest) ProtoMessage()               {}
func (*InputRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *InputRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InputRequest) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type InputResponse struct {
	Config *ResourceConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *InputResponse) Reset()                    { *m = InputResponse{} }
func (m *InputResponse) String() string            { return proto1.CompactTextString(m) }
func (*InputResponse) ProtoMessage()               {}
func (*InputResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *InputResponse) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type ReadDataApplyRequest struct {
	Info *InstanceInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Diff *InstanceDiff `protobuf:"bytes,2,opt,name=diff" json:"diff,omitempty"`
}

func (m *ReadDataApplyRequest) Reset()                    { *m = ReadDataApplyRequest{} }
func (m *ReadDataApplyRequest) String() string            { return proto1.CompactTextString(m) }
func (*ReadDataApplyRequest) ProtoMessage()               {}
func (*ReadDataApplyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ReadDataApplyRequest) GetInfo() *InstanceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReadDataApplyRequest) GetDiff() *InstanceDiff {
	if m != nil {
		return m.Diff
	}
	return nil
}

type ReadDataApplyResponse struct {
	State *InstanceState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (m *ReadDataApplyResponse) Reset()                    { *m = ReadDataApplyResponse{} }
func (m *ReadDataApplyResponse) String() string            { return proto1.CompactTextString(m) }
func (*ReadDataApplyResponse) ProtoMessage()               {}
func (*ReadDataApplyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ReadDataApplyResponse) GetState() *InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

type ReadDataDiffRequest struct {
	Info   *InstanceInfo   `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Config *ResourceConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *ReadDataDiffRequest) Reset()                    { *m = ReadDataDiffRequest{} }
func (m *ReadDataDiffRequest) String() string            { return proto1.CompactTextString(m) }
func (*ReadDataDiffRequest) ProtoMessage()               {}
func (*ReadDataDiffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ReadDataDiffRequest) GetInfo() *InstanceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReadDataDiffRequest) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type ReadDataDiffResponse struct {
	Diff *InstanceDiff `protobuf:"bytes,1,opt,name=diff" json:"diff,omitempty"`
}

func (m *ReadDataDiffResponse) Reset()                    { *m = ReadDataDiffResponse{} }
func (m *ReadDataDiffResponse) String() string            { return proto1.CompactTextString(m) }
func (*ReadDataDiffResponse) ProtoMessage()               {}
func (*ReadDataDiffResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ReadDataDiffResponse) GetDiff() *InstanceDiff {
	if m != nil {
		return m.Diff
	}
	return nil
}

type RefreshRequest struct {
	Info  *InstanceInfo  `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	State *InstanceState `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
}

func (m *RefreshRequest) Reset()                    { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string            { return proto1.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()               {}
func (*RefreshRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RefreshRequest) GetInfo() *InstanceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RefreshRequest) GetState() *InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

type RefreshResponse struct {
	State *InstanceState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (m *RefreshResponse) Reset()                    { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string            { return proto1.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()               {}
func (*RefreshResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RefreshResponse) GetState() *InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

type ResourceType struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Importable bool   `protobuf:"varint,2,opt,name=importable" json:"importable,omitempty"`
}

func (m *ResourceType) Reset()                    { *m = ResourceType{} }
func (m *ResourceType) String() string            { return proto1.CompactTextString(m) }
func (*ResourceType) ProtoMessage()               {}
func (*ResourceType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ResourceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceType) GetImportable() bool {
	if m != nil {
		return m.Importable
	}
	return false
}

type ResourcesResponse struct {
	Resources []*ResourceType `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
}

func (m *ResourcesResponse) Reset()                    { *m = ResourcesResponse{} }
func (m *ResourcesResponse) String() string            { return proto1.CompactTextString(m) }
func (*ResourcesResponse) ProtoMessage()               {}
func (*ResourcesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ResourcesResponse) GetResources() []*ResourceType {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ValidateRequest struct {
	Config *ResourceConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *ValidateRequest) Reset()                    { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string            { return proto1.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()               {}
func (*ValidateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ValidateRequest) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type ValidateResponse struct {
	Warnings []string `protobuf:"bytes,1,rep,name=warnings" json:"warnings,omitempty"`
	Errors   []string `protobuf:"bytes,2,rep,name=errors" json:"errors,omitempty"`
}

func (m *ValidateResponse) Reset()                    { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string            { return proto1.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()               {}
func (*ValidateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ValidateResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *ValidateResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ValidateDataSourceRequest struct {
	Type   string          `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Config *ResourceConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *ValidateDataSourceRequest) Reset()                    { *m = ValidateDataSourceRequest{} }
func (m *ValidateDataSourceRequest) String() string            { return proto1.CompactTextString(m) }
func (*ValidateDataSourceRequest) ProtoMessage()               {}
func (*ValidateDataSourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ValidateDataSourceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ValidateDataSourceRequest) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type ValidateResourceRequest struct {
	Type   string          `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Config *ResourceConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *ValidateResourceRequest) Reset()                    { *m = ValidateResourceRequest{} }
func (m *ValidateResourceRequest) String() string            { return proto1.CompactTextString(m) }
func (*ValidateResourceRequest) ProtoMessage()               {}
func (*ValidateResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ValidateResourceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ValidateResourceRequest) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type ProvisionerApplyRequest struct {
	// need to add Output
	State  *InstanceState  `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Config *ResourceConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *ProvisionerApplyRequest) Reset()                    { *m = ProvisionerApplyRequest{} }
func (m *ProvisionerApplyRequest) String() string            { return proto1.CompactTextString(m) }
func (*ProvisionerApplyRequest) ProtoMessage()               {}
func (*ProvisionerApplyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ProvisionerApplyRequest) GetState() *InstanceState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ProvisionerApplyRequest) GetConfig() *ResourceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*InstanceInfo)(nil), "proto.InstanceInfo")
	proto1.RegisterType((*InstanceState)(nil), "proto.InstanceState")
	proto1.RegisterType((*EphemeralState)(nil), "proto.EphemeralState")
	proto1.RegisterType((*ResourceAttrDiff)(nil), "proto.ResourceAttrDiff")
	proto1.RegisterType((*InstanceDiff)(nil), "proto.InstanceDiff")
	proto1.RegisterType((*ApplyRequest)(nil), "proto.ApplyRequest")
	proto1.RegisterType((*ApplyResponse)(nil), "proto.ApplyResponse")
	proto1.RegisterType((*ResourceConfig)(nil), "proto.ResourceConfig")
	proto1.RegisterType((*ConfigureRequest)(nil), "proto.ConfigureRequest")
	proto1.RegisterType((*DataSourcesResponse)(nil), "proto.DataSourcesResponse")
	proto1.RegisterType((*DiffRequest)(nil), "proto.DiffRequest")
	proto1.RegisterType((*DiffResponse)(nil), "proto.DiffResponse")
	proto1.RegisterType((*GetSchemaRequest)(nil), "proto.GetSchemaRequest")
	proto1.RegisterType((*GetSchemaResponse)(nil), "proto.GetSchemaResponse")
	proto1.RegisterType((*ImportStateRequest)(nil), "proto.ImportStateRequest")
	proto1.RegisterType((*ImportStateResponse)(nil), "proto.ImportStateResponse")
	proto1.RegisterType((*InputRequest)(nil), "proto.InputRequest")
	proto1.RegisterType((*InputResponse)(nil), "proto.InputResponse")
	proto1.RegisterType((*ReadDataApplyRequest)(nil), "proto.ReadDataApplyRequest")
	proto1.RegisterType((*ReadDataApplyResponse)(nil), "proto.ReadDataApplyResponse")
	proto1.RegisterType((*ReadDataDiffRequest)(nil), "proto.ReadDataDiffRequest")
	proto1.RegisterType((*ReadDataDiffResponse)(nil), "proto.ReadDataDiffResponse")
	proto1.RegisterType((*RefreshRequest)(nil), "proto.RefreshRequest")
	proto1.RegisterType((*RefreshResponse)(nil), "proto.RefreshResponse")
	proto1.RegisterType((*ResourceType)(nil), "proto.ResourceType")
	proto1.RegisterType((*ResourcesResponse)(nil), "proto.ResourcesResponse")
	proto1.RegisterType((*ValidateRequest)(nil), "proto.ValidateRequest")
	proto1.RegisterType((*ValidateResponse)(nil), "proto.ValidateResponse")
	proto1.RegisterType((*ValidateDataSourceRequest)(nil), "proto.ValidateDataSourceRequest")
	proto1.RegisterType((*ValidateResourceRequest)(nil), "proto.ValidateResourceRequest")
	proto1.RegisterType((*ProvisionerApplyRequest)(nil), "proto.ProvisionerApplyRequest")
	proto1.RegisterEnum("proto.DiffAttrType", DiffAttrType_name, DiffAttrType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Provider service

type ProviderClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*Empty, error)
	DataSources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DataSourcesResponse, error)
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	ImportState(ctx context.Context, in *ImportStateRequest, opts ...grpc.CallOption) (*ImportStateResponse, error)
	Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error)
	ReadDataApply(ctx context.Context, in *ReadDataApplyRequest, opts ...grpc.CallOption) (*ReadDataApplyResponse, error)
	ReadDataDiff(ctx context.Context, in *ReadDataDiffRequest, opts ...grpc.CallOption) (*ReadDataDiffResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	Resources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResourcesResponse, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	ValidateDataSource(ctx context.Context, in *ValidateDataSourceRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	ValidateResource(ctx context.Context, in *ValidateResourceRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type providerClient struct {
	cc *grpc.ClientConn
}

func NewProviderClient(cc *grpc.ClientConn) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	out := new(ApplyResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Provider/Configure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) DataSources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DataSourcesResponse, error) {
	out := new(DataSourcesResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/DataSources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error) {
	out := new(DiffResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/Diff", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/GetSchema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) ImportState(ctx context.Context, in *ImportStateRequest, opts ...grpc.CallOption) (*ImportStateResponse, error) {
	out := new(ImportStateResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/ImportState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error) {
	out := new(InputResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/Input", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) ReadDataApply(ctx context.Context, in *ReadDataApplyRequest, opts ...grpc.CallOption) (*ReadDataApplyResponse, error) {
	out := new(ReadDataApplyResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/ReadDataApply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) ReadDataDiff(ctx context.Context, in *ReadDataDiffRequest, opts ...grpc.CallOption) (*ReadDataDiffResponse, error) {
	out := new(ReadDataDiffResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/ReadDataDiff", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/Refresh", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Resources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResourcesResponse, error) {
	out := new(ResourcesResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/Resources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Provider/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) ValidateDataSource(ctx context.Context, in *ValidateDataSourceRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/ValidateDataSource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) ValidateResource(ctx context.Context, in *ValidateResourceRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := grpc.Invoke(ctx, "/proto.Provider/ValidateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Provider service

type ProviderServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	Configure(context.Context, *ConfigureRequest) (*Empty, error)
	DataSources(context.Context, *Empty) (*DataSourcesResponse, error)
	Diff(context.Context, *DiffRequest) (*DiffResponse, error)
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	ImportState(context.Context, *ImportStateRequest) (*ImportStateResponse, error)
	Input(context.Context, *InputRequest) (*InputResponse, error)
	ReadDataApply(context.Context, *ReadDataApplyRequest) (*ReadDataApplyResponse, error)
	ReadDataDiff(context.Context, *ReadDataDiffRequest) (*ReadDataDiffResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	Resources(context.Context, *Empty) (*ResourcesResponse, error)
	Stop(context.Context, *Empty) (*Empty, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	ValidateDataSource(context.Context, *ValidateDataSourceRequest) (*ValidateResponse, error)
	ValidateResource(context.Context, *ValidateResourceRequest) (*ValidateResponse, error)
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_DataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).DataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/DataSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).DataSources(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Diff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/GetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_ImportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).ImportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/ImportState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).ImportState(ctx, req.(*ImportStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Input_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Input(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Input",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Input(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_ReadDataApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDataApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).ReadDataApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/ReadDataApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).ReadDataApply(ctx, req.(*ReadDataApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_ReadDataDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDataDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).ReadDataDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/ReadDataDiff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).ReadDataDiff(ctx, req.(*ReadDataDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Resources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Resources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Resources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Resources(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_ValidateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).ValidateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/ValidateDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).ValidateDataSource(ctx, req.(*ValidateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_ValidateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).ValidateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provider/ValidateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).ValidateResource(ctx, req.(*ValidateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _Provider_Apply_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Provider_Configure_Handler,
		},
		{
			MethodName: "DataSources",
			Handler:    _Provider_DataSources_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _Provider_Diff_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _Provider_GetSchema_Handler,
		},
		{
			MethodName: "ImportState",
			Handler:    _Provider_ImportState_Handler,
		},
		{
			MethodName: "Input",
			Handler:    _Provider_Input_Handler,
		},
		{
			MethodName: "ReadDataApply",
			Handler:    _Provider_ReadDataApply_Handler,
		},
		{
			MethodName: "ReadDataDiff",
			Handler:    _Provider_ReadDataDiff_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Provider_Refresh_Handler,
		},
		{
			MethodName: "Resources",
			Handler:    _Provider_Resources_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Provider_Stop_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Provider_Validate_Handler,
		},
		{
			MethodName: "ValidateDataSource",
			Handler:    _Provider_ValidateDataSource_Handler,
		},
		{
			MethodName: "ValidateResource",
			Handler:    _Provider_ValidateResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// Client API for Provisioner service

type ProvisionerClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	Apply(ctx context.Context, in *ProvisionerApplyRequest, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type provisionerClient struct {
	cc *grpc.ClientConn
}

func NewProvisionerClient(cc *grpc.ClientConn) ProvisionerClient {
	return &provisionerClient{cc}
}

func (c *provisionerClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := grpc.Invoke(ctx, "/proto.Provisioner/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerClient) Apply(ctx context.Context, in *ProvisionerApplyRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Provisioner/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Provisioner/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Provisioner service

type ProvisionerServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	Apply(context.Context, *ProvisionerApplyRequest) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
}

func RegisterProvisionerServer(s *grpc.Server, srv ProvisionerServer) {
	s.RegisterService(&_Provisioner_serviceDesc, srv)
}

func _Provisioner_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provisioner/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioner_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionerApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provisioner/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).Apply(ctx, req.(*ProvisionerApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioner_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Provisioner/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provisioner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Provisioner",
	HandlerType: (*ProvisionerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Provisioner_Validate_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Provisioner_Apply_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Provisioner_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

func init() { proto1.RegisterFile("plugin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcf, 0x73, 0xd3, 0xc6,
	0x17, 0xff, 0x4a, 0x8e, 0x63, 0xeb, 0x49, 0x76, 0xcc, 0x3a, 0x10, 0x21, 0x18, 0xbe, 0x46, 0xb4,
	0x83, 0x87, 0x0e, 0x69, 0x6b, 0xa6, 0x05, 0xca, 0x40, 0xa1, 0x49, 0x60, 0x52, 0x86, 0xc0, 0x28,
	0x81, 0x5e, 0x98, 0x7a, 0x84, 0xb5, 0x8e, 0x35, 0xd8, 0x92, 0x90, 0xd6, 0x71, 0x7d, 0xec, 0xa9,
	0x97, 0x5e, 0x7a, 0xe8, 0xa1, 0xe7, 0x4e, 0x4f, 0xfd, 0x27, 0x3b, 0xbb, 0xda, 0xd5, 0x4f, 0x83,
	0xe3, 0xb4, 0x9c, 0xbc, 0xfb, 0xf4, 0xf6, 0xed, 0x7b, 0x9f, 0xf7, 0x79, 0xef, 0xad, 0x41, 0x0b,
	0xc6, 0xd3, 0x63, 0xd7, 0xdb, 0x0e, 0x42, 0x9f, 0xf8, 0xa8, 0xca, 0x7e, 0xcc, 0x1a, 0x54, 0xf7,
	0x26, 0x01, 0x99, 0x9b, 0x87, 0xa0, 0xed, 0x7b, 0x11, 0xb1, 0xbd, 0x01, 0xde, 0xf7, 0x86, 0x3e,
	0x6a, 0x82, 0xec, 0x3a, 0xba, 0xd4, 0x91, 0xba, 0x8a, 0x25, 0xbb, 0x0e, 0x42, 0xb0, 0x46, 0xe6,
	0x01, 0xd6, 0x65, 0x26, 0x61, 0x6b, 0xf4, 0x7f, 0x50, 0x27, 0xbe, 0x33, 0x1d, 0xe3, 0x7e, 0x60,
	0x93, 0x91, 0x5e, 0xe9, 0x54, 0xba, 0x8a, 0x05, 0xb1, 0xe8, 0x85, 0x4d, 0x46, 0xe6, 0x2f, 0x32,
	0x34, 0x84, 0xd5, 0x43, 0x62, 0x13, 0x5c, 0x32, 0xbb, 0x0b, 0x60, 0x13, 0x12, 0xba, 0x6f, 0xa6,
	0x04, 0x47, 0xba, 0xdc, 0xa9, 0x74, 0xd5, 0xde, 0x27, 0xb1, 0x8b, 0xdb, 0xb9, 0x93, 0xdb, 0x8f,
	0x12, 0xb5, 0x3d, 0x8f, 0x84, 0x73, 0x2b, 0x73, 0x0e, 0xdd, 0x02, 0x05, 0x07, 0x23, 0x3c, 0xc1,
	0xa1, 0x3d, 0xd6, 0x2b, 0x1d, 0xa9, 0xab, 0xf6, 0xce, 0x73, 0x23, 0x7b, 0x42, 0xce, 0xac, 0x58,
	0xa9, 0x1e, 0x8d, 0x68, 0x82, 0x89, 0xad, 0xaf, 0x75, 0xa4, 0xae, 0x66, 0xb1, 0x35, 0xd2, 0xa1,
	0x46, 0x6c, 0xd7, 0x23, 0xd8, 0xd1, 0xab, 0x1d, 0xa9, 0x5b, 0xb7, 0xc4, 0xd6, 0xb8, 0x0f, 0x1b,
	0x05, 0x0f, 0x50, 0x0b, 0x2a, 0x6f, 0xf1, 0x9c, 0x07, 0x43, 0x97, 0x68, 0x13, 0xaa, 0x27, 0xf6,
	0x78, 0x1a, 0xa3, 0xa4, 0x59, 0xf1, 0xe6, 0x1b, 0xf9, 0x8e, 0x64, 0xfe, 0x29, 0x41, 0x33, 0xef,
	0x4a, 0x82, 0xa8, 0x94, 0x41, 0xf4, 0x21, 0x28, 0x03, 0xdf, 0xf3, 0xfa, 0xae, 0x37, 0xf4, 0x39,
	0x1a, 0xd7, 0x16, 0x06, 0xb2, 0xbd, 0xe3, 0x7b, 0x1e, 0x4d, 0x54, 0x0c, 0x46, 0x7d, 0xc0, 0xb7,
	0xc6, 0x3d, 0x68, 0xe4, 0x3e, 0x2d, 0xf3, 0x52, 0xc9, 0x7a, 0xf9, 0xb3, 0x0c, 0x2d, 0x0b, 0x47,
	0xfe, 0x34, 0x1c, 0x60, 0x1a, 0xed, 0xae, 0x3b, 0x1c, 0x52, 0x03, 0xfe, 0x58, 0xe4, 0x8c, 0x2e,
	0xa9, 0xc4, 0xc3, 0x33, 0x7e, 0x9c, 0x2e, 0xd1, 0x55, 0xd0, 0x3c, 0x3c, 0xeb, 0x0f, 0xfc, 0x49,
	0x30, 0xa5, 0xe0, 0x55, 0x18, 0x78, 0xaa, 0x87, 0x67, 0x3b, 0x5c, 0x44, 0xc9, 0x42, 0x55, 0x42,
	0x3c, 0xf1, 0x4f, 0xb0, 0xc3, 0x50, 0xaf, 0x5b, 0xe0, 0xe1, 0x99, 0x15, 0x4b, 0xd0, 0x25, 0x50,
	0xa8, 0x02, 0xfe, 0x89, 0x84, 0x36, 0x43, 0x5f, 0xb3, 0xea, 0x1e, 0x9e, 0xed, 0xd1, 0x3d, 0xbd,
	0x20, 0xc4, 0xef, 0xa6, 0x6e, 0x88, 0xa3, 0x3e, 0xbd, 0x7b, 0x3d, 0xbe, 0x40, 0xc8, 0x0e, 0xf0,
	0x0c, 0x5d, 0x06, 0x25, 0xc2, 0x5e, 0xe4, 0x12, 0xf7, 0x04, 0xeb, 0x35, 0xf6, 0x3d, 0x15, 0xa0,
	0xeb, 0x1c, 0xed, 0x7a, 0x47, 0xea, 0x36, 0x7b, 0x6d, 0x0e, 0x2a, 0x0d, 0x90, 0x06, 0x7a, 0x34,
	0x0f, 0x70, 0x9c, 0x02, 0xf3, 0x6f, 0x39, 0xad, 0x04, 0x16, 0xff, 0x4e, 0x8e, 0xa2, 0x52, 0x2e,
	0x29, 0x59, 0xc5, 0x0f, 0x32, 0x54, 0x87, 0x9a, 0x83, 0x23, 0x12, 0xfa, 0x73, 0x06, 0x5b, 0xdd,
	0x12, 0x5b, 0x74, 0x1d, 0x36, 0xf8, 0xb2, 0xef, 0xe0, 0xc0, 0x8f, 0x12, 0xf4, 0x9a, 0x5c, 0xbc,
	0x1b, 0x4b, 0xb3, 0x8a, 0x82, 0xa3, 0x6b, 0x39, 0xc5, 0xa3, 0x58, 0x9a, 0x10, 0xbb, 0x9a, 0x12,
	0xdb, 0x78, 0x75, 0x1a, 0xfa, 0xde, 0xcc, 0x12, 0x43, 0xed, 0x6d, 0xf1, 0x20, 0x8b, 0x8c, 0xc8,
	0x32, 0xe6, 0x57, 0x09, 0xb4, 0x47, 0x41, 0x30, 0x9e, 0x5b, 0xf8, 0xdd, 0x14, 0x47, 0x84, 0xe2,
	0xcc, 0xc8, 0x2b, 0x31, 0x13, 0xed, 0x02, 0x4e, 0x94, 0x96, 0x16, 0x53, 0x40, 0x37, 0xa0, 0x1a,
	0x51, 0x26, 0xf3, 0xcb, 0x36, 0x17, 0x15, 0xbd, 0x15, 0xab, 0x50, 0xa3, 0x8e, 0x3b, 0x1c, 0xf2,
	0xd2, 0x6e, 0x2f, 0x00, 0xdf, 0x62, 0x0a, 0xe6, 0x3d, 0x68, 0x70, 0x6f, 0xa2, 0xc0, 0xf7, 0x22,
	0x9c, 0xde, 0x22, 0x2d, 0xbd, 0xc5, 0xfc, 0x5d, 0x86, 0xa6, 0x88, 0x75, 0xc7, 0xf7, 0x86, 0xee,
	0x31, 0xba, 0x06, 0x0d, 0xc1, 0xe9, 0xfe, 0x5b, 0x3c, 0x8f, 0xd3, 0xaf, 0x58, 0x9a, 0x10, 0x3e,
	0xc5, 0xf3, 0x08, 0x7d, 0x01, 0x95, 0xd0, 0x9e, 0xf1, 0x72, 0xbd, 0x52, 0x00, 0x2d, 0x36, 0xb4,
	0x6d, 0xd9, 0xb3, 0x98, 0x14, 0x54, 0x15, 0xdd, 0x85, 0xf5, 0x01, 0x93, 0xb3, 0x9e, 0xa9, 0xf6,
	0xae, 0x2e, 0x3e, 0x14, 0xff, 0xc4, 0xe7, 0xf8, 0x01, 0xe3, 0x6b, 0xa8, 0x0b, 0x5b, 0xab, 0x34,
	0x20, 0xe3, 0x2e, 0xa8, 0x19, 0x73, 0x2b, 0xf5, 0x2e, 0x0b, 0x5a, 0xf1, 0xd1, 0x69, 0x88, 0x45,
	0x9a, 0x1f, 0xc0, 0x46, 0xc8, 0x9d, 0xed, 0xf3, 0x50, 0xa4, 0x5c, 0xdf, 0xcd, 0x87, 0x62, 0x35,
	0xc3, 0xdc, 0xde, 0xbc, 0x03, 0xed, 0x5d, 0x9b, 0xd8, 0x87, 0x4c, 0x16, 0x25, 0xe9, 0xba, 0x0a,
	0x9a, 0x63, 0x13, 0xbb, 0x1f, 0xeb, 0x0a, 0xb8, 0x55, 0x27, 0x55, 0x35, 0x7f, 0x93, 0x40, 0x65,
	0x19, 0xff, 0x98, 0x84, 0xbb, 0x99, 0x49, 0xd0, 0x07, 0xa2, 0xe2, 0x4a, 0xe6, 0x6d, 0xd0, 0x62,
	0x97, 0x78, 0x18, 0x82, 0xaf, 0xd2, 0x32, 0xbe, 0xbe, 0x86, 0xd6, 0x13, 0x4c, 0x0e, 0x07, 0x23,
	0x3c, 0xb1, 0x45, 0x40, 0x9f, 0x42, 0x02, 0x56, 0x9f, 0x76, 0x24, 0x81, 0x42, 0x43, 0x48, 0x69,
	0xb3, 0x8a, 0x4a, 0x50, 0xc9, 0x65, 0xa8, 0x3e, 0x83, 0x73, 0x19, 0xeb, 0xdc, 0xb7, 0x0b, 0xb0,
	0x1e, 0x31, 0x09, 0xf3, 0x4e, 0xb3, 0xf8, 0xce, 0x7c, 0x06, 0x68, 0x7f, 0x12, 0xf8, 0x21, 0x89,
	0x81, 0xe0, 0xce, 0x14, 0xe7, 0xb5, 0x40, 0x5b, 0x5e, 0x82, 0xb6, 0xf9, 0x08, 0xda, 0x39, 0x73,
	0xe5, 0x7a, 0xac, 0x2c, 0xab, 0xc7, 0x67, 0xb4, 0x11, 0x07, 0x53, 0x52, 0xf6, 0xa5, 0xca, 0x7c,
	0x49, 0x93, 0x24, 0x9f, 0x26, 0x49, 0x0f, 0xe8, 0x5b, 0x84, 0x99, 0xe3, 0xbe, 0xa4, 0xe7, 0xa5,
	0xd3, 0x9c, 0x1f, 0xc1, 0xa6, 0x85, 0x6d, 0x87, 0xd2, 0xf6, 0x6c, 0x1d, 0x4f, 0xb0, 0x42, 0x5e,
	0xc6, 0x8a, 0x1d, 0x38, 0x5f, 0xb8, 0xe9, 0x0c, 0xdd, 0x6c, 0x02, 0x6d, 0x61, 0xe4, 0x4c, 0xe5,
	0xb2, 0x22, 0xba, 0xdf, 0xa6, 0xe8, 0x9c, 0xad, 0x14, 0x30, 0x6d, 0xbe, 0xc3, 0x10, 0x47, 0xa3,
	0x8f, 0x59, 0xd9, 0xe6, 0x7d, 0xd8, 0x48, 0xae, 0x39, 0x03, 0xaa, 0xdf, 0x81, 0x66, 0x65, 0xca,
	0x90, 0xce, 0x5a, 0xcf, 0x9e, 0x24, 0x8f, 0x38, 0xba, 0x46, 0x57, 0x00, 0x5c, 0x46, 0x7d, 0xfb,
	0xcd, 0x18, 0xf3, 0x71, 0x9f, 0x91, 0x98, 0x8f, 0xe1, 0x9c, 0xb0, 0x91, 0x76, 0xbe, 0x2f, 0x41,
	0x11, 0xf5, 0x2d, 0x1e, 0x19, 0xed, 0x02, 0xe2, 0xec, 0x91, 0x92, 0x6a, 0x99, 0x0f, 0x61, 0xe3,
	0x95, 0x3d, 0x76, 0x9d, 0x4c, 0xb9, 0xae, 0x48, 0xe9, 0xc7, 0xd0, 0x4a, 0x2d, 0x70, 0x47, 0x0c,
	0xa8, 0xcf, 0xec, 0xd0, 0x73, 0xbd, 0x63, 0xd1, 0x78, 0x92, 0x3d, 0xed, 0x1d, 0x38, 0x0c, 0xfd,
	0x50, 0x74, 0x1b, 0xbe, 0x33, 0x7f, 0x84, 0x8b, 0xc2, 0x4e, 0xda, 0xd5, 0x85, 0x4f, 0x8b, 0xde,
	0xb9, 0x2b, 0x92, 0xeb, 0x35, 0x6c, 0x65, 0xfc, 0xfc, 0xaf, 0xad, 0x13, 0xd8, 0x7a, 0x11, 0xfa,
	0x27, 0x6e, 0xe4, 0xfa, 0x1e, 0x0e, 0x73, 0xb5, 0xbd, 0x02, 0x35, 0x56, 0xbc, 0xf5, 0x46, 0x2f,
	0x9e, 0x19, 0xe2, 0xf5, 0x89, 0x54, 0xa8, 0xbd, 0x3c, 0x78, 0x7a, 0xf0, 0xfc, 0x87, 0x83, 0xd6,
	0xff, 0x90, 0x02, 0xd5, 0xfd, 0x83, 0x17, 0x2f, 0x8f, 0x5a, 0x12, 0x02, 0x58, 0x7f, 0xfe, 0xf2,
	0x88, 0xae, 0xe5, 0xde, 0x1f, 0x35, 0xa8, 0x33, 0x57, 0x1d, 0x1c, 0xa2, 0x1e, 0x54, 0x99, 0xaf,
	0x48, 0xf0, 0x24, 0xeb, 0xb9, 0xb1, 0x99, 0x17, 0xf2, 0xe4, 0xf6, 0x40, 0x49, 0x46, 0x39, 0x12,
	0xef, 0xbb, 0xe2, 0x70, 0x37, 0x34, 0xf1, 0x97, 0x83, 0xfe, 0x33, 0x44, 0xb7, 0x41, 0xcd, 0x8c,
	0x6a, 0x94, 0xfb, 0x68, 0x18, 0xe2, 0x21, 0xbd, 0x60, 0x98, 0x7f, 0x0e, 0x6b, 0xec, 0x01, 0x8d,
	0x32, 0x8f, 0x6d, 0x71, 0x45, 0x3b, 0x27, 0xe3, 0x07, 0x1e, 0x80, 0x92, 0xcc, 0xab, 0xc4, 0xbb,
	0xe2, 0x7c, 0x34, 0xf4, 0xf2, 0x07, 0x7e, 0x7e, 0x17, 0xd4, 0xcc, 0xcc, 0x41, 0x17, 0x45, 0xb6,
	0x4a, 0x63, 0x2d, 0x71, 0x7b, 0xd1, 0x88, 0xea, 0x41, 0x95, 0xcd, 0x09, 0x94, 0x76, 0x9c, 0x74,
	0x08, 0x19, 0x9b, 0x79, 0x21, 0x3f, 0xf3, 0x3d, 0x34, 0x72, 0x1d, 0x1b, 0x5d, 0x4a, 0x92, 0x5f,
	0x9e, 0x18, 0xc6, 0xe5, 0xc5, 0x1f, 0xb9, 0xad, 0x27, 0xb4, 0xc5, 0xa4, 0x9d, 0x14, 0x19, 0x05,
	0xed, 0x2c, 0x8c, 0x97, 0x16, 0x7e, 0xe3, 0x86, 0xee, 0x40, 0x8d, 0xb7, 0x3a, 0x94, 0x72, 0x31,
	0xdb, 0x61, 0x8d, 0x0b, 0x45, 0x31, 0x3f, 0x79, 0x0b, 0x94, 0xa4, 0x43, 0x15, 0x12, 0xae, 0x17,
	0x58, 0x9d, 0xa6, 0xdb, 0x84, 0xb5, 0x43, 0xe2, 0x07, 0x05, 0xfd, 0x3c, 0x97, 0xee, 0x41, 0x5d,
	0x14, 0x32, 0x12, 0x97, 0x17, 0x7a, 0x98, 0xb1, 0x55, 0x92, 0xf3, 0x0b, 0x9e, 0x03, 0x2a, 0x77,
	0x19, 0xd4, 0x29, 0xa8, 0x97, 0x1a, 0xd0, 0xfb, 0x0d, 0x3e, 0xcd, 0xb5, 0xbf, 0xd8, 0xdc, 0x95,
	0xb2, 0xf2, 0xa9, 0x8c, 0xf5, 0xfe, 0x92, 0x40, 0xcd, 0xb4, 0x91, 0x7f, 0x17, 0xea, 0x57, 0xa2,
	0xb6, 0x85, 0x3b, 0xef, 0x69, 0x50, 0x05, 0x78, 0x4f, 0x91, 0x82, 0x37, 0xeb, 0x6c, 0x73, 0xeb,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x86, 0x7e, 0x53, 0x0f, 0x12, 0x00, 0x00,
}
